### ISSUE TITLE
Reminder to use new line characters

### ISSUE THREAD

**Issue by henrikmdev** [Marko-Pajic/Hangman#5]
https://github.com/Marko-Pajic/ConsoleApp4/blob/67bb01ad28c0f3a80b008ac0de89b988b3c2b8fe/Program.cs#L28
https://github.com/Marko-Pajic/ConsoleApp4/blob/67bb01ad28c0f3a80b008ac0de89b988b3c2b8fe/Program.cs#L36
https://github.com/Marko-Pajic/ConsoleApp4/blob/67bb01ad28c0f3a80b008ac0de89b988b3c2b8fe/Program.cs#L58
https://github.com/Marko-Pajic/ConsoleApp4/blob/67bb01ad28c0f3a80b008ac0de89b988b3c2b8fe/Program.cs#L72

Just a reminder that you can use "\n" in other Console.WriteLine(...) calls to add new lines instead of using a blank Console.WriteLine(); Doing this you can remove some extra lines from your code.

**Comment by Marko-Pajic** [comment]
Hi Henrik. I managed to replace line 58 and 72. I dont see how its possible on line 28 and 36. Can you help me?

**Comment by henrikmdev** [comment]
Yeah, 28 and 36 are okay because there isn't another Write call you can use a new line character. Unless you can create a new message there for example asking the user to input a key.
