### ISSUE TITLE
Use proper string constructor

### ISSUE THREAD

**Issue by henrikmdev** [Marko-Pajic/Hangman#7]
https://github.com/Marko-Pajic/ConsoleApp4/blob/67bb01ad28c0f3a80b008ac0de89b988b3c2b8fe/Program.cs#L50

Use the proper string constructor like so:
string allCharExist = new string(guessedWord);

**Comment by Marko-Pajic** [comment]
HI Henrik! I took the string part out because VS suggested the simplification. Why is that?

**Comment by henrikmdev** [comment]
VS suggested it because it's not necessary to have it as the compiler knows what the data type is since you declared it as a string. I prefer you to have the string part because that's the standard way of doing it, but I spoke with the other coaches and they're okay if you leave it out too. So it's your call :)
